### ISSUE TITLE
FetchContent_Declare in Cmake 3.11+

### ISSUE THREAD

**Issue by Thodoris1999** [sloretz/darknet_vendor#5]
I am using CMake version 3.16 and CMake cannot recognize `FetchContent_Declare`.

It seems that in CMake 3.11+ the CMake module 'FetchContent' is meant to be used, which was added in CMake 3.11.

In the [examples](https://cmake.org/cmake/help/latest/module/FetchContent.html#examples), it is shown that it is also necessary to also add the line `include(FetchContent)`.

I added the line mentioned and it works as expected.

So possible solutions is to either remove the `if(CMAKE_VERSION VERSION_LESS "3.11")` statement around the include local `FetchContent` [declaration](https://github.com/ros2/darknet_vendor/blob/master/CMakeLists.txt#L15) in order to use the local implementation always, or add
```
else()
include(FetchContent)
```
and use CMake's implementation in 3.11+

**Comment by sloretz** [comment]
Thanks for reporting @Thodoris1999! Would you mind trying out #6 on your machine?

**Comment by Thodoris1999** [comment]
It worked
