### ISSUE TITLE
OpenCV build issues (IplImage does not name a type)

### ISSUE THREAD

**Issue by nightduck** [sloretz/darknet_vendor#8]
Building with instructions out of the box, I get a bunch of openCV related errors, starting with the one in the title. Passing DARKNET_OPENCV=Off fixes these errors (see my other issue for the CUDA problems).

Is there a particular version of OpenCV that's recommended? I'm using 4.2

**Comment by sloretz** [comment]
I used OpenCV 3.2 on Ubuntu Bionic. It looks like there's an upstream PR to support OpenCV 4.0 : https://github.com/pjreddie/darknet/pull/1348, but this vendor package should probably [switch the most popular fork](https://twitter.com/pjreddie/status/1253891078182199296): https://github.com/AlexeyAB/darknet/

**Comment by nightduck** [comment]
I'll try both 3.2 and using the AlexeyAB fork. For the latter approach, is it as simple as changing [this line](https://github.com/ros2/darknet_vendor/blob/4d609295280bf9b50cde69bb9a483a8db839ba0b/CMakeLists.txt#L26)?

**Comment by sloretz** [comment]
Maybe, that line and the one above with the git tag might do it. I'm not sure if there have been added or removed files though. It looks like the fork has it's own CMakeLists.txt, so it might make sense to use that instead of the CMake wrapper here.

**Comment by nightduck** [comment]
Uninstalling 4.2 and using Ubuntu's default 3.2 resolves this issue. I did not test AlexeyAB's fork with this wrapper, but it built with 4.2 by itself, so I don't see why this repo wouldn't work if you switched to his.
